# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
# first 10 terms will be
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
# even-valued terms.
class FibonacciCalculator:
    def __init__(self):
        # We pre-populate the cache with the first two numbers
        # to handle the base cases of the Fibonacci sequence.
        self.cache = {0: 0, 1: 1}

    def calculate(self, n: int) -> int:
        """Calculates the nth Fibonacci number using memoization."""
        if n < 0:
            raise ValueError("Fibonacci numbers are not defined for negative integers.")

        # Check if the value is already in our cache
        if n in self.cache:
            return self.cache[n]

        # Otherwise, calculate it recursively and store the result
        self.cache[n] = self.calculate(n - 1) + self.calculate(n - 2)
        return self.cache[n]

    def clear_cache(self):
        """Resets the cache back to base cases."""
        self.cache = {0: 0, 1: 1}

def calculate_even_fibonacci_numbers(target, f: FibonacciCalculator):
    even_fibonacci_sum = 0
    current_fibonacci = 0
    i = 0
    while current_fibonacci <= target:
        current_fibonacci = f.calculate(i)
        if current_fibonacci % 2 == 0:
            even_fibonacci_sum += current_fibonacci
        i+=1
    return even_fibonacci_sum

f_calc = FibonacciCalculator()
print(calculate_even_fibonacci_numbers(4_000_000, f_calc))